### ISSUE TITLE
Chisel 2.9.3.9 crash

### ISSUE THREAD

**Issue by WeaselOnaStick** [twothe/DaVincing#10]
http://paste.ee/p/QQHA3

**Comment by twothe** [comment]
`two.davincing.sculpture.SculptureBlock cannot be cast to team.chisel.ctmlib.ICTMBlock`

This is the essential part. This is duo to an incompatibility with Chisel (which has issues with several other mods).

For the moment I recommend to set chisel blocks on the blacklist in the Davincing config file. Afair there was such a list on the forum for copy & paste.

**Comment by twothe** [comment]
Closed because duplicate of #9
