### ISSUE TITLE
Crash with Colored Lights mod

### ISSUE THREAD

**Issue by xeronut** [twothe/DaVincing#4]
Hello!  I has crash: http://pastebin.com/TQk7svyz

I got this when chipping the first piece off of a piece of vanilla Stone.  Oddly enough I had started chiseling a Limestone block from the Chisel2 mod first to see if it'd crash, and it did not - but the block turned transparent as seen in this pic: http://imgur.com/Byi1vFG

There was a similar crash with MinePainter 0.3.0f1 I logged for the Colored Lights compatibility list, reproduced with only the CLC and MinePainter mods: http://pastebin.com/9VyxLz3s

Note the CLC mod is indeed still beta, but hopefully these logs give you some insight into any future issues once that is no longer the case.  Thanks for your time!

**Comment by twothe** [comment]
This is actually a bug with Colored Lights. That mod assumes that everything that is IBlockAccess must be a ChunkCache, which is bad coding.

You would have to ask the author of Colored Lights to fix that.

**Comment by xeronut** [comment]
Thank you for the response!  I'll bring your suggestion to CptSpaceToaster (dev for Colored Lights/Chisel2) and go from there.
