### ISSUE TITLE
Crash with DaVincing 1.2

### ISSUE THREAD

**Issue by xeronut** [twothe/DaVincing#5]
http://pastebin.com/2LhUyQqs - crashes on running the game, doesn't even get to the main menu.

**Comment by xeronut** [comment]
Update - similar crash without using Colored Lights: http://pastebin.com/A0yX7cd1
Update2 - crash on Forge 1291 without OptiFine, FastCraft or Colored Lights: http://pastebin.com/VAqpKF6Q

**Comment by twothe** [comment]
This is related to Java 8. Strange, I was sure this would be backward compatible.

**Comment by twothe** [comment]
Fixed with 1710.1.3.

I will from now on use Java 7 to prevent these kind of issues.
