### ISSUE TITLE
Sculptures made of Chisel2 blocks are transparent in-world (but not inventory)

### ISSUE THREAD

**Issue by xeronut** [twothe/DaVincing#6]
Yeah.. title.  Here's a pic demonstrating that it only happens on certain blocks: http://i.imgur.com/dPEdJHb.png

Sculptures render properly in my hand as seen in pic, but when placed in world they are invisible.  Hitboxes still appear when chiseling tools are held and sculpture pieces have no rendering issues in world, just the sculpture itself.

I've gone through my mod list (179 mods currently) and this is the only mod that has this issue.

Let me know if you need a comprehensive list of blocks that don't work, or any other info.

**Comment by xeronut** [comment]
Update:  I am an idiot - I had OptiFine U B5 installed the whole time.  I thought I had removed it, but I was wrong - removing it fixed everything and sculptures appeared again.  FastCraft doesn't hinder this mod at all by the way, in case that was a concern.  I'll raise an issue in the OptiFine thread as well if that's preferable.

Blocks NOT affected were the ice and packed ice variants.  All other Chisel2 blocks had the transparency issues.  No crashes or performance wonkiness, just transparent blocks as in the pic above.

**Comment by twothe** [comment]
I don't think the OptiFine guys can fix that, but it is good to know that there is an issue with DaVincing and Optifine since many ppl use that.
