### ISSUE TITLE
Shaders with DaVincing & Chisel2

### ISSUE THREAD

**Issue by Nziner** [twothe/DaVincing#7]
When I try to work with a chisel on block from Chiesl2.
http://pastebin.com/HNFhsqDe
DaVincing-1710.1.5
Chisel2-2.3.5.31
ShadersModCore-v2.3.28-mc1.7.10-f

**Comment by twothe** [comment]
This issue is caused by the Shaders Mod and the error is inside the Shader's Mod code. I don't think I can fix this, but I'll have a look.

**Comment by twothe** [comment]
Workaround in place with 1710.1.8
