### ISSUE TITLE
Crash with Chisel2 and Davincing

### ISSUE THREAD

**Issue by xeronut** [twothe/DaVincing#9]
http://pastebin.com/LGsE7pZf

Crashed upon using the saw on a block of plain, worldgenned marble (no CTM).  I'm pretty sure this is the first time I've tried breaking a Chisel2 block up since the big 2.5 update that redid their CTM logic, hence this is a delayed discovery.  Everything else is unaffected, just Chisel2 being obtuse.

Chisel 2.9.3.9 (the fork of Chisel2 headed by some of the members of the Chisel2 team) also crashes in a similar manner, so it may be something with their CTMLib that's embedded in the mod.  Thanks for your time!

**Comment by xeronut** [comment]
To sidestep this issue until a fix is implemented, here is a DaVincing config file that simply blacklists all Chisel2 blocks: http://pastebin.com/MzNVYMtD

**Comment by tterrag1098** [comment]
https://github.com/tterrag1098/minepainter/commit/600fc21cff7d16bef8dbeddc3fc7024b835a538f

**Comment by xeronut** [comment]
Nice!  I'll test this as soon as it's patched into Davincing (Minepainter itself is depreciated, as the dev has been MIA for about a year).  Thank you for giving this a stab!

**Comment by tterrag1098** [comment]
Well I would have made a PR if @twothe had forked the repo properly. The old mod was open source you know...

**Comment by twothe** [comment]
I read through the PR but you changed way too many things. Please either create a PR with just the essential changes, otherwise I will try to find some time to extract and include your fixes.

**Comment by twothe** [comment]
Workaround in place with 1710.1.8
